import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LangProvider } from "@/components/contexts/LangContext";
import LangChooser from "@/components/LangChooser";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        {/* Fullscreen background container */}
        <div
          className="min-h-screen bg-cover bg-center"
          style={{ backgroundImage: "url('/images/bg.jpg')" }}
        >
          <LangProvider>
            <main className="min-h-screen flex flex-col items-center justify-center">
              {children}
            </main>
          </LangProvider>
        </div>
      </body>
    </html>
  );
}
